{"name": "test_mul[无效用例]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 12", "trace": "self = <pytest_practice1.test_calculator.TestCalculator object at 0x00000254AA90FB38>\nget_calculator = <pytest_practice1.calculatorCode.calculator.Calculator object at 0x00000254AA8A25C0>, a = 3, b = 4, expect = 5\n\n    @pytest.mark.second_to_last\n    @allure.story(\"测试乘法计算功能\")\n    @pytest.mark.parametrize(\"a,b,expect\", get_datas()[4], ids=get_datas()[5])  # 参数化 , ids命名测试用例结果\n    def test_mul(self,get_calculator, a, b, expect):\n        print(\"测试相乘\")\n        result = round(get_calculator.mul(a, b),2)\n>       assert expect == result\nE       assert 5 == 12\n\ntest_calculator.py:56: AssertionError"}, "attachments": [{"name": "stdout", "source": "be280185-ed85-4561-9478-cbbac2722dd5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "3"}, {"name": "b", "value": "4"}, {"name": "expect", "value": "5"}], "start": 1598328853327, "stop": 1598328853329, "uuid": "1687bbbc-e156-4ad6-ac5b-9380e275716d", "historyId": "0c9ae9107ed8991c331a2e862f41cb87", "testCaseId": "0840940e086021f091827e595274da59", "fullName": "test_calculator.TestCalculator#test_mul", "labels": [{"name": "feature", "value": "计算器功能测试"}, {"name": "story", "value": "测试乘法计算功能"}, {"name": "tag", "value": "second_to_last"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "DESKTOP-O9I37L5"}, {"name": "thread", "value": "5836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}